### ISSUE TITLE
Promise/Async detection is sketchy

### ISSUE THREAD

**Issue by robludwig** [goodeggs/stream-worker#5]
[This](https://github.com/goodeggs/stream-worker/blob/02787c95aca30ad121fe442279c8c5b7979cd4a9/stream-worker.js#L9) line, which exists to differentiate between traditional async/callback flows and promise-based flows, is causing some issues for me. I'm using a different library to wrap my work function, and that library uses a pattern where it returns a function that takes no named arguments, but calls `function.apply(arguments)`. This [causes](https://github.com/xavi-/node-simple-rate-limiter/issues/2) a traditional args/callback function to appear as a promisified function to your library, and it doesn't end up getting its callback passed.

Is there a way to add an options parameter to stream-worker to indicate whether I want to use promises? I can do it myself in a PR if you'd like.

**Comment by bobzoller** [comment]
@demands thoughts?

**Comment by hazeledmands** [comment]
Interesting, this sounds like a fine thing to do. What if the API looked like this?:

``` js
// with promises:
streamWorker(stream, promiseFunction, {promises: true, concurrency: 10});

// with callbacks:
streamWorker(stream, callbackFunction, {promises: false, concurrency: 10}, doneFunction));
```

I'm fine with `promises` defaulting to `false`.
